# Generated by Django 2.0.4 on 2018-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(max_length=10, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(default='xxxxxxxx-xxxx', max_length=13, verbose_name='Organisationsnummer'),
        ),
    ]
