# Generated by Django 2.0.3 on 2018-05-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180504_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coname',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='Företagsnamn'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(default='', max_length=13, null=True, verbose_name='Organisationsnummer'),
        ),
    ]
