# Generated by Django 2.0.3 on 2018-05-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180504_1350'),
        ('accounts', '0004_auto_20180504_1143'),
    ]

    operations = [
    ]
