# Generated by Django 2.0.4 on 2018-05-14 08:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.CharField(default=None, max_length=300, null=True, verbose_name='Firmanamn')),
                ('jurform', models.CharField(default=None, max_length=2, null=True, verbose_name='Juridisk form')),
                ('firstname', models.CharField(default=None, max_length=80, null=True, verbose_name='Förnamn')),
                ('surname', models.CharField(default=None, max_length=100, null=True, verbose_name='Efternamn')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_coord', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Mediankoordinat')),
                ('area', models.DecimalField(decimal_places=12, default=0, max_digits=24, null=True, verbose_name='Area')),
                ('municipality', models.CharField(default='', max_length=16, verbose_name='Kommun')),
                ('district', models.CharField(default='', max_length=40, verbose_name='Trakt')),
                ('unity', models.CharField(default='', max_length=4, verbose_name='Enhet')),
                ('sign', models.CharField(default='', max_length=1, null=True, verbose_name='Tecken')),
                ('block', models.CharField(default='', max_length=4, verbose_name='Block')),
                ('price_fa', models.CharField(default='', max_length=36, null=True, verbose_name='Köpeskilling fast egendom')),
                ('currency_fa', models.CharField(default='', max_length=5, null=True, verbose_name='Valuta fast egendom')),
                ('price_lo', models.CharField(default='', max_length=36, null=True, verbose_name='Köpeskilling lös egendom')),
                ('currency_lo', models.CharField(default='', max_length=5, null=True, verbose_name='Valuta lös egendom')),
                ('price_date', models.CharField(default='', max_length=8, null=True, verbose_name='Försäljningsdatum')),
                ('coord_e', models.DecimalField(decimal_places=3, default=0, max_digits=30, null=True, verbose_name='Koord E')),
                ('coord_n', models.DecimalField(decimal_places=3, default=0, max_digits=30, null=True, verbose_name='Koord N')),
                ('leaseholders', models.ManyToManyField(to='map.LeaseHolder')),
            ],
            options={
                'ordering': ('coord_n', 'coord_e'),
            },
        ),
        migrations.CreateModel(
            name='PropertyBoarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internid', models.BigIntegerField()),
                ('detaljtyp', models.CharField(max_length=11)),
                ('gdat', models.CharField(max_length=16)),
                ('adat', models.CharField(max_length=16)),
                ('xyfel', models.BigIntegerField()),
                ('metodplan', models.IntegerField()),
                ('flyghojd', models.BigIntegerField()),
                ('undskala', models.BigIntegerField()),
                ('knid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=13, null=True, verbose_name='Organisationsnummer')),
                ('coname', models.CharField(default=None, max_length=300, null=True, verbose_name='Firmanamn')),
                ('jurform', models.CharField(default=None, max_length=2, null=True, verbose_name='Juridisk form')),
                ('firstname', models.CharField(default=None, max_length=80, null=True, verbose_name='Förnamn')),
                ('surname', models.CharField(default=None, max_length=100, null=True, verbose_name='Efternamn')),
            ],
            options={
                'ordering': ('coname', 'surname'),
            },
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfProperty', models.CharField(max_length=100, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastighetsbeteckning', models.CharField(max_length=32)),
                ('area', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(to='map.PropertyOwner'),
        ),
    ]
