# Generated by Django 2.0.4 on 2018-05-07 08:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_coord', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Mediankoordinat')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyBoarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internid', models.BigIntegerField()),
                ('detaljtyp', models.CharField(max_length=10)),
                ('gdat', models.CharField(max_length=16)),
                ('adat', models.CharField(max_length=16)),
                ('xyfel', models.BigIntegerField()),
                ('metodplan', models.IntegerField()),
                ('flyghojd', models.BigIntegerField()),
                ('undskala', models.BigIntegerField()),
                ('knid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=13, null=True, verbose_name='Organisationsnummer')),
                ('coname', models.CharField(default=None, max_length=300, null=True, verbose_name='Firmanamn')),
                ('jurform', models.CharField(default=None, max_length=2, null=True, verbose_name='Juridisk form')),
                ('firstname', models.CharField(default=None, max_length=80, null=True, verbose_name='Förnamn')),
                ('surname', models.CharField(default=None, max_length=100, null=True, verbose_name='Efternamn')),
            ],
            options={
                'ordering': ('coname',),
            },
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfProperty', models.CharField(max_length=100, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastighetsbeteckning', models.CharField(max_length=32)),
                ('area', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(to='map.PropertyOwner'),
        ),
    ]
