# Generated by Django 2.0.3 on 2018-05-04 11:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='coord_e',
        ),
        migrations.RemoveField(
            model_name='property',
            name='coord_n',
        ),
        migrations.AddField(
            model_name='property',
            name='med_coord',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Mediankoordinat'),
        ),
    ]
