# Generated by Django 2.0.3 on 2018-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseholder',
            name='currency_fa',
            field=models.CharField(default='', max_length=5, null=True, verbose_name='Valuta fast egendom'),
        ),
        migrations.AddField(
            model_name='leaseholder',
            name='currency_lo',
            field=models.CharField(default='', max_length=5, null=True, verbose_name='Valuta lös egendom'),
        ),
        migrations.AddField(
            model_name='leaseholder',
            name='price_date',
            field=models.CharField(default='', max_length=8, null=True, verbose_name='Försäljningsdatum'),
        ),
        migrations.AddField(
            model_name='leaseholder',
            name='price_fa',
            field=models.CharField(default='', max_length=36, null=True, verbose_name='Köpeskilling fast egendom'),
        ),
        migrations.AddField(
            model_name='leaseholder',
            name='price_lo',
            field=models.CharField(default='', max_length=36, null=True, verbose_name='Köpeskilling lös egendom'),
        ),
    ]
