# Generated by Django 2.0.3 on 2018-05-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_n', models.CharField(default=None, max_length=30, null=True, verbose_name='N-koordinat')),
                ('coord_e', models.CharField(default=None, max_length=30, null=True, verbose_name='E-koordinat')),
            ],
            options={
                'ordering': ('coord_n',),
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=13, null=True, verbose_name='Organisationsnummer')),
                ('coname', models.CharField(default=None, max_length=300, null=True, verbose_name='Firmanamn')),
                ('jurform', models.CharField(default=None, max_length=2, null=True, verbose_name='Juridisk form')),
                ('firstname', models.CharField(default=None, max_length=80, null=True, verbose_name='Förnamn')),
                ('surname', models.CharField(default=None, max_length=100, null=True, verbose_name='Efternamn')),
            ],
            options={
                'ordering': ('coname',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(to='map.PropertyOwner'),
        ),
    ]
