# Generated by Django 2.0.4 on 2018-05-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_propertyboarder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyboarder',
            options={'verbose_name_plural': 'Property Boarders'},
        ),
    ]
