# Generated by Django 2.0.3 on 2018-05-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180503_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owners',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyOwner',
        ),
    ]
