# Generated by Django 2.0.3 on 2018-05-04 11:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180504_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='med_coord',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Mediankoordinat'),
        ),
    ]
