# Generated by Django 2.0.3 on 2018-05-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180516_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseholder',
            name='jurform',
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='jurform',
        ),
    ]
