# Generated by Django 2.0.3 on 2018-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20180516_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='taxation_land',
            field=models.CharField(default='', max_length=9, null=True, verbose_name='Taxeringsvärde på byggnad(er)'),
        ),
        migrations.AddField(
            model_name='property',
            name='taxation_year',
            field=models.CharField(default='', max_length=4, null=True, verbose_name='Taxeringsår'),
        ),
    ]
