# Generated by Django 2.0.3 on 2018-05-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20180504_1403'),
        ('map', '0002_auto_20180504_1136'),
    ]

    operations = [
    ]
