# Generated by Django 2.0.3 on 2018-05-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20180510_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='currency_lo',
            field=models.CharField(default='', max_length=5, null=True, verbose_name='Valuta lös egendom'),
        ),
    ]
