# Generated by Django 2.0.3 on 2018-05-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_merge_20180504_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyBoarder',
        ),
    ]
