# Generated by Django 2.0.3 on 2018-05-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20180510_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.IntegerField(default=0, max_length=17, verbose_name='Datum och löpnummer'),
        ),
    ]
