# Generated by Django 2.0.3 on 2018-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20180516_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='taxation_build',
            field=models.CharField(default='', max_length=9, null=True, verbose_name='Taxeringsvärde på byggnad(er)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='taxation_land',
            field=models.CharField(default='', max_length=7, null=True, verbose_name='Taxeringsvärde på mark'),
        ),
    ]
