# Generated by Django 2.0.4 on 2018-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20180516_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseholder',
            name='coname',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Firmanamn'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='firstname',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='Förnamn'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='surname',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Efternamn'),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='coname',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Firmanamn'),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='firstname',
            field=models.CharField(default='', max_length=80, null=True, verbose_name='Förnamn'),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='surname',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Efternamn'),
        ),
    ]
