# Generated by Django 2.0.4 on 2018-05-07 07:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_delete_propertyboarder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBoarder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internid', models.BigIntegerField()),
                ('detaljtyp', models.CharField(max_length=10)),
                ('gdat', models.CharField(max_length=16)),
                ('adat', models.CharField(max_length=16)),
                ('xyfel', models.BigIntegerField()),
                ('metodplan', models.IntegerField()),
                ('flyghojd', models.BigIntegerField()),
                ('undskala', models.BigIntegerField()),
                ('knid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
