# Generated by Django 2.0.3 on 2018-05-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_property_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.IntegerField(default=0, verbose_name='Datum och löpnummer'),
        ),
    ]
