# Generated by Django 2.0.4 on 2018-05-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_propertyboarder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('med_coord',)},
        ),
    ]
