# Generated by Django 2.0.3 on 2018-05-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20180511_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('date', 'coord_n', 'coord_e')},
        ),
    ]
