# Generated by Django 2.0.4 on 2018-05-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20180516_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Punkt',
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
    ]
