# Generated by Django 2.0.3 on 2018-05-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20180511_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('coord_n', 'coord_e')},
        ),
    ]
