# Generated by Django 2.0.4 on 2018-05-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20180507_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('coord_n', 'coord_e')},
        ),
        migrations.AddField(
            model_name='property',
            name='coord_e',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Koord E'),
        ),
        migrations.AddField(
            model_name='property',
            name='coord_n',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Koord N'),
        ),
    ]
