# Generated by Django 2.0.3 on 2018-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20180511_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='date',
        ),
        migrations.AddField(
            model_name='property',
            name='price_date',
            field=models.IntegerField(default=0, null=True, verbose_name='Försäljningsdatum'),
        ),
    ]
