# Generated by Django 2.0.4 on 2018-05-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20180507_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('coord_n',)},
        ),
    ]
