# Generated by Django 2.0.4 on 2018-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20180507_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('coord_n', 'coord_e')},
        ),
        migrations.AlterField(
            model_name='property',
            name='coord_e',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30, null=True, verbose_name='Koord E'),
        ),
        migrations.AlterField(
            model_name='property',
            name='coord_n',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30, null=True, verbose_name='Koord N'),
        ),
    ]
