# Generated by Django 2.0.3 on 2018-05-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20180511_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.CharField(default=None, max_length=300, null=True, verbose_name='Firmanamn')),
                ('jurform', models.CharField(default=None, max_length=2, null=True, verbose_name='Juridisk form')),
                ('firstname', models.CharField(default=None, max_length=80, null=True, verbose_name='Förnamn')),
                ('surname', models.CharField(default=None, max_length=100, null=True, verbose_name='Efternamn')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='leaseholders',
            field=models.ManyToManyField(to='map.LeaseHolder'),
        ),
    ]
