# Generated by Django 2.0.3 on 2018-05-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20180507_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyowner',
            options={'ordering': ('coname', 'surname')},
        ),
    ]
