# Generated by Django 2.0.4 on 2018-05-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20180507_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyowner',
            options={'ordering': ('coname', 'surname')},
        ),
        migrations.AlterField(
            model_name='propertyboarder',
            name='detaljtyp',
            field=models.CharField(max_length=11),
        ),
    ]
