# Generated by Django 2.0.3 on 2018-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20180509_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Area'),
            preserve_default=False,
        ),
    ]
