# Generated by Django 2.0.3 on 2018-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_property_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, null=True, verbose_name='Area'),
        ),
    ]
