# Generated by Django 2.0.3 on 2018-05-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20180510_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='municipality',
            field=models.CharField(default='', max_length=16, verbose_name='Kommun'),
        ),
    ]
